#!/usr/bin/env bash
set -euo pipefail

echo "[resume] Ensuring the Nix daemon is available"
sudo systemctl start nix-daemon.socket
sudo chmod 0711 /nix/var/nix/daemon-socket

echo "[resume] Verifying nix-shell"
nix-shell --version
nix --extra-experimental-features nix-command store ping
